/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerImp;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.Assignment;
import model.Student;
import model.TaiKhoan;

/**
 *
 * @author Administrator
 */
public class DangNhapFrm extends javax.swing.JFrame {

    /**
     * Creates new form DangNhapFrm
     */
    private List<TaiKhoan> dstk;
    public List<Student> dssv;
    public List<Assignment> asms ;
    private ControllerImp controll;
    
    public DangNhapFrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        controll =new ControllerImp();
        dstk =new ArrayList();
        dssv = new ArrayList();
        asms = new ArrayList();
        dssv.addAll(controll.readDataFromFile("SV.DAT"));
        asms.addAll(controll.readDataFromFile("PHANCONG.DAT"));
        dstk.addAll(controll.readDataFromFile("TKSV.txt"));
        if(dstk.isEmpty()) getTk();
    }
    
    public void getTk(){
        List<TaiKhoan> list=new ArrayList();
        for(Student sv : dssv){
            TaiKhoan tk =new TaiKhoan(""+sv.getId(), "123456");
            list.add(tk);
        }
        controll.writeToFile(list, "TKSV.txt");
    }
    public boolean check(List<TaiKhoan> list,String tk,char[] mk){
        for (TaiKhoan taiKhoan : list) {
            if(taiKhoan.getId().compareTo(tk)==0){
                char[] kttk = taiKhoan.getMatkhau().toCharArray();
                return Arrays.equals(kttk, mk);
            }
        }
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tktx = new javax.swing.JTextField();
        mktx = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tài khoản");

        jLabel2.setText("Mật khẩu");

        jButton1.setText("Đăng nhập");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Nhóm 18");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tktx)
                            .addComponent(mktx, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addGap(69, 69, 69)))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tktx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mktx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String tk = tktx.getText();
        char[] mk = mktx.getPassword();
      
        if(checkAdm(tk, mk)){
            HomeFrm home = new HomeFrm();
            home.setVisible(true);
            this.dispose();
        }
        else if(check(dstk,tk,mk)){
            this.dispose();
            boolean ok = true;
            StudentView stv = new StudentView(this, rootPaneCheckingEnabled);
            for(Assignment as : asms){
                if(as.getStudent().getId()==Integer.parseInt(tk)){
                    stv.settextTentx(as.getStudent().getTen());
                    stv.settextLoptx(as.getStudent().getLop());
                    stv.showtb(as);
                    
                    ok =false;
                    break;
                }
            }
            if(ok){
                for(Student student: dssv){
                    if(student.getId()==Integer.parseInt(tk)){
                        stv.settextTentx(student.getTen());
                        stv.settextLoptx(student.getLop());
                        
                        break;
                    }
                }
            }
            stv.setLocationRelativeTo(null);
            stv.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Sai TK hoac MK");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhapFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField mktx;
    private javax.swing.JTextField tktx;
    // End of variables declaration//GEN-END:variables

    private boolean checkAdm(String tk, char[] mk) {
        String checkPass = "admin";
        char[] arrCheck = checkPass.toCharArray();
        if(tk.equals("admin") && Arrays.equals(arrCheck, mk)){
                return true;
            }
        return false;
    }
}
